name: Test & Release

on:
  push:
    tags:
      - "v*"

jobs:
  test-and-release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-hyperlight-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-hyperlight
          path: |
            ~/.gitlibs
            ~/.m2

      - name: Install Nix
        uses: cachix/install-nix-action@v18

      - run: nix-build

      - run: nix-shell --run "clj -T:build ci :snapshot false"

      - name: Deploy release jar
        run: nix-shell --run "clj -T:build deploy :snapshot false"
        env:
          CLOJARS_PASSWORD: ${{secrets.CLOJARS_PASSWORD}}
          CLOJARS_USERNAME: ${{secrets.CLOJARS_USERNAME}}
